project_id = "nsbytsrwtokhfrbhwoph"

[functions.notify-restaurant-registration]
verify_jwt = true

[functions.food-recommendations]
verify_jwt = false

[functions.mood-food-analyzer]
verify_jwt = false
